### ISSUE TITLE
Access: Creating permissions for the new group

### ISSUE THREAD

**Issue by philipcj** [MicrosoftDocs/office-developer-client-docs#102]
This document doesn't explain how to GRANT permissions to the new group. The GRANT page explains how to grant permissions to tables, but the users of this group still cannot log into MS ACCESS because the OPEN DATABASE permission isn't set.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0fc9db14-5dfe-2d15-c4dd-92f01483e005
* Version Independent ID: 2a801b28-dd74-b620-6ee8-e44c7a6956c4
* Content: [CREATE USER or GROUP statement (Microsoft Access SQL)](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/create-user-or-group-statement-microsoft-access-sql)
* Content Source: [docs/access/desktop-database-reference/create-user-or-group-statement-microsoft-access-sql.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/access/desktop-database-reference/create-user-or-group-statement-microsoft-access-sql.md)
* Product: **access**
* Technology: **custom-web-app**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Hi @philipcj, have you tried asking this question to the developer community at StackOverflow? For example, I think [this question](https://stackoverflow.com/questions/55513842/how-to-grant-database-open-permissions-programatically-in-ms-access) was asked to the Access developer community. This forum is for bugs in documentation. For programming questions, we recommend that you refer to Stack. Thanks!

**Comment by lindalu-MSFT** [comment]
Because we are not longer updating Access custom-web-app documentation, I'm closing this issue.
