### ISSUE TITLE
Project: javascript Code errors

### ISSUE THREAD

**Issue by hugomr89** [MicrosoftDocs/office-developer-client-docs#103]
There are some errors on the javascript code, the variable 'hostUrl' is declared twice, it should only be declared as a global variable, also when validation the response on the onMessage function the 'if (length = 67)' is assigning the value 67 not evaluating it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830ee4d6-a873-cd56-f37c-a4a16585152b
* Version Independent ID: a152837d-8142-2e55-b7d7-8fbd7ac11a13
* Content: [Get the project ID in an add-in part on a Project Details Page](https://docs.microsoft.com/en-us/office/client-developer/project/get-the-project-id-in-an-add-in-part-on-a-project-details-page#feedback)
* Content Source: [docs/project/get-the-project-id-in-an-add-in-part-on-a-project-details-page.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/project/get-the-project-id-in-an-add-in-part-on-a-project-details-page.md)
* Product: **project**
* Technology: **dev-overview**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@hugomr89 Can you please provide the steps to repro the errors?
