### ISSUE TITLE
RAND() missing from list of volatile functions?

### ISSUE THREAD

**Issue by hjallig** [MicrosoftDocs/office-developer-client-docs#108]
I believe the RAND() function is also a volatile function, but it is not listed as such above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07dca75d-b334-fba8-b5e9-6fde72e75318
* Version Independent ID: fd2046d6-c55e-6b28-fc84-d88fd71e5e59
* Content: [Excel Recalculation](https://docs.microsoft.com/en-us/office/client-developer/excel/excel-recalculation#feedback)
* Content Source: [docs/excel/excel-recalculation.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/excel/excel-recalculation.md)
* Product: **excel**
* Technology: **excel-xll**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@hjallig Hi, thanksfor your question. As of Excel 2010, Excel uses the [Mersenne Twister algorithm](https://en.wikipedia.org/wiki/Mersenne_Twister) (MT19937) to generate random numbers. Please see this [RAND function - Office support](https://support.office.com/en-us/article/rand-function-4cbfa695-8869-4788-8d90-021ea9f5be73) article. Thanks, linda

**Comment by hjallig** [comment]
Thanks for the information @lindalu-MSFT , but that was not the question. There wasn't even a question :)

I was simply pointing out that in the documentation you list 8 Excel functions as volatile, and RAND() is not one of them, despite evidently being a volatile function as - per the definition - "one whose value cannot be assumed to be the same from one moment to the next even if none of its arguments (if it takes any) has changed".

Hope this helps.
