### ISSUE TITLE
[LOC] "長さ" needs to be replaced with "LENGTH"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#120]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions

**Comment by hyoshioka0128** [comment]
![STRING_LENGTH](https://user-images.githubusercontent.com/40815708/57056632-ac412200-6cde-11e9-913b-f153e91df06f.png)

**Comment by OfficeGlobal** [comment]
related issues: #121 | #122

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed

**Comment by Linda-Editor** [comment]
@0fficeglobal When you fix these, please attach the fixed label and close the issue. I've done this one; please do the others.
