### ISSUE TITLE
[LOC] "ら" needs to be replaced with "LOCATE"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#121]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions
![STRING_LOCATE](https://user-images.githubusercontent.com/40815708/57056614-8a479f80-6cde-11e9-985d-6ee215534b62.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed
