### ISSUE TITLE
[LOC] "副" needs to be replaced with "SUBSTRING"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#122]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions
![STRING_SUBSTRING](https://user-images.githubusercontent.com/40815708/57056679-f4f8db00-6cde-11e9-9fed-2109aa0c0a63.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed
