### ISSUE TITLE
[LOC] "窓" needs to be replaced with "FLOOR"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#124]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions
![Numeric_Floor](https://user-images.githubusercontent.com/40815708/57121705-2becf080-6db4-11e9-8d83-f0946b028785.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed
