### ISSUE TITLE
[LOC] "ログイン" needs to be replaced with "LOG" 

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#125]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions
![Numeric_LOG](https://user-images.githubusercontent.com/40815708/57121779-9736c280-6db4-11e9-979b-3733bfba40fb.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed
