### ISSUE TITLE
[LOC] "限度" needs to be replaced with "CEILING"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#126]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions
![Numeric_CEILING](https://user-images.githubusercontent.com/40815708/57121865-29d76180-6db5-11e9-8fd1-55ac04331976.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed
