### ISSUE TITLE
[LOC] "面上" needs to be replaced with "COS"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#127]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions
![Numeric_COS](https://user-images.githubusercontent.com/40815708/57121896-5d19f080-6db5-11e9-9817-e91da5fb1d91.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed
