### ISSUE TITLE
[LOC] "モダン" needs to be replaced with "MOD"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#128]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions
![Numeric_MOD](https://user-images.githubusercontent.com/40815708/57121959-b124d500-6db5-11e9-9173-07e1e849ec67.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed
