### ISSUE TITLE
[LOC] "\*" needs to be replaced with "EXP"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#129]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions
![Numeric_EXP](https://user-images.githubusercontent.com/40815708/57122008-ee896280-6db5-11e9-80b7-8802034093dc.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed
