### ISSUE TITLE
[LOC] "付け" needs to be replaced with "SIGN"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#130]
https://docs.microsoft.com/ja-jp/office/client-developer/access/desktop-database-reference/odbc-scalar-functions
![Numeric_SIGN](https://user-images.githubusercontent.com/40815708/57122059-2e504a00-6db6-11e9-8f30-c2716f838ccb.png)

**Comment by OfficeGlobal** [comment]
@hyoshioka0128 value has been updated. The issue is fixed
