### ISSUE TITLE
Schema reference in "Manipulate the Visio file format programmatically"

### ISSUE THREAD

**Issue by nicmartello** [MicrosoftDocs/office-developer-client-docs#135]
I received a NullReferenceException following the code in: 

"https://docs.microsoft.com/en-us/office/client-developer/visio/how-to-manipulate-the-visio-file-format-programmatically"

Checking the rels file in the visio package I was using, the schema reference in the visio file uses http:// instead of https:// 
i.e. in the sample code it should be 
http://schemas.microsoft.com/visio/2010/relationships/document
instead of what is currently there:
https://schemas.microsoft.com/visio/2010/relationships/document

I think the schema reference url in the sample code may have been mistakenly updated with the 4th Oct http:// to https:// document update in GitHub 

Thanks.

**Comment by AlexHedley** [comment]
[0cd6a8a](https://github.com/MicrosoftDocs/office-developer-client-docs/commit/0cd6a8af5ad2d44c7d54df53cbb17f48913d1de1)

**Comment by Linda-Editor** [comment]
@nicmartello Thanks for pointing this out. I reverted all the schemas.microsoft.com links on this page to use http://. Changes will be live momentarily.
