### ISSUE TITLE
[LOC] Back-Translation "さん" → "cm"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#149]
https://docs.microsoft.com/ja-jp/office/client-developer/visio/about-units-of-measure-visio-shapesheet-reference
![visio_unit](https://user-images.githubusercontent.com/40815708/57499937-6a3a6080-731c-11e9-8984-4236cc2a8c27.png)

**Comment by OfficeGlobal** [comment]
@MollyMalone 

We are working on a fix (Bug 3358938)
