### ISSUE TITLE
[LOC] Back-Translation "解決 id" → "ResolutionID"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/office-developer-client-docs#157]
https://docs.microsoft.com/ja-jp/office/client-developer/visio/authorentry_type-complextypevisio-xml
![authorentry_type-complextypevisio-xml](https://user-images.githubusercontent.com/40815708/57825284-1ecef900-77d9-11e9-9c98-1cbefa641ecc.png)

**Comment by Linda-Editor** [comment]
@OfficeGlobal There are numerous issues that need to be assigned to you. I've assigned some of them, but I don't have time to do all of them. Please go to the repo and assign the OfficeGlobal tag to the rest of them, and then follow the usual procedure of assigning "fixed" and then closing the issue after you have fixed it. Thanks, and let me know if you have any questions.
