### ISSUE TITLE
[LOC] Invalid MD notation

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/office-developer-client-docs#184]
Hello, 
 we noticed an invalid MD notation for sections mentioned in repro steps, could you please check the article and update it?

**Repro steps:**
 1. Go to https://github.com/MicrosoftDocs/office-developer-client-docs/blob/live/docs/outlook/selecting-an-api-or-technology-for-developing-solutions-for-outlook.md
 2. Check sections
  - _Figure 2. Major baseline scenarios supported by the Outlook object model or PIA_
  - _Figure 3. Additional scenarios supported by the object model or PIA since Outlook 2007_

e.g.:
![image](https://user-images.githubusercontent.com/47977325/58022993-016a9980-7b0f-11e9-89ae-680e60fafd57.png)

**Comment by Linda-Editor** [comment]
@OfficeGlobal Thanks. I'll look into this. Posting the live link for reference: https://docs.microsoft.com/en-us/office/client-developer/outlook/selecting-an-api-or-technology-for-developing-solutions-for-outlook

**Comment by Linda-Editor** [comment]
@OfficeGlobal I've fixed this page; changes are now live: https://docs.microsoft.com/en-us/office/client-developer/outlook/selecting-an-api-or-technology-for-developing-solutions-for-outlook#decision-factors-for-the-object-model-or-pia

I removed the images (commented them out) and added the links as bulleted lists (the images added no value); the lists are merely links to other sections on the page. Let me know if you have any questions.
