### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by barnam3** [MicrosoftDocs/office-developer-client-docs#189]
Line 171 reads
Set rest = dbs.OpenRecordset

Should be
Set rst = dbs.OpenRecordset

Adding Option Explicit in the module or VBE settings throws on this, but the average user won't know that.

![Set rest typo](https://user-images.githubusercontent.com/43246807/58751767-2a751d80-8471-11e9-8fc9-8610dca949bc.PNG)

**Comment by Linda-Editor** [comment]
@barnam3 Thanks for submitting this. Can you send a link to the page where this occurs? Thanks.

**Comment by Linda-Editor** [comment]
@barnam3 Nevermind, I found it at Database.OpenRecordset method (DAO). Also found one at Recordset.Filter property. Fixed both. Changes will be live shortly.

**Comment by barnam3** [comment]
I thought the issue was tied to the page - that's what brought me here. Doc>Edit>Issue Tab>New Issue. But I guess they aren't connected that way... sorry.
