### ISSUE TITLE
Access: Code example is incorrect

### ISSUE THREAD

**Issue by Markgi999** [MicrosoftDocs/office-developer-client-docs#194]
Help - Database.OpenRecordset method (DAO) 
Dim dbs As DAO.Database
Dim **qdf** As DAO.QueryDef
Dim rst As DAO.Recordset

Set dbs = CurrentDb

'Get the parameter query
Set **qdf** = dbs.QueryDefs("qryMyParameterQuery")

'Supply the parameter value
qdf.Parameters("EnterStartDate") = Date
qdf.Parameters("EnterEndDate") = Date + 7

'Open a Recordset based on the parameter query
Set rst = qdf.OpenRecordset()
Link

**Comment by lindalu-MSFT** [comment]
@Markgi999 Can you please include the link to the documentation? I'll see if I can update the doc bug. Sorry it's taken so long to get back to you on this. I'm not sure who is responding to this repo, I'll try to find out. Thanks!

**Comment by Markgi999** [comment]
https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/database-openrecordset-method-dao?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Den-US%26k%3Dk(dao360.chm1052939)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice%2Fclient-developer%2Faccess%2Fdesktop-database-reference%2Fdatabase-openrecordset-method-dao%3Ff1url%3Dhttps%253A%252F%252Fmsdn.microsoft.com%252Fquery%252Fdev11.query%253FappId%253DDev11IDEF1%2526l%253Den-US%2526k%253Dk(dao360.chm1052939)%253Bk(TargetFrameworkMoniker-Office.Version%253Dv16)%2526rd%253Dtrue&data=04%7C01%7Cmarkgi%40microsoft.com%7C7902dc7093e7409a6d7308d6fa69c9bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636971729591074162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=axySCgCP%2FsuEEKPx7epwCpzeQVPF2TugH2pomTXzb1g%3D&reserved=0>

@Linda Lu Cannon<mailto:notifications@github.com>

________________________________

**Comment by lindalu-MSFT** [comment]
@Markgi999 Thanks for the fast reply! Can you provide the steps to repro? I'm not sure what part of the code sample is incorrect. Need to verify so I can fix it in the documentation.

**Comment by Markgi999** [comment]
It's the first code example.

________________________________

**Comment by lindalu-MSFT** [comment]
@Markgi999 OK thanks, but what is throwing the error? Have you set up the DAO reference correctly?

**Comment by Markgi999** [comment]
As far as I can see, it's just a typo.

________________________________

**Comment by lindalu-MSFT** [comment]
@Markgi999 Please provide the following information. I'm not good at guessing.
1. Line of code with the typo. 
2. Suggested correction.

**Comment by lindalu-MSFT** [comment]
@Markgi999 You're also welcome to fix it yourself and submit a PR! Thanks

**Comment by Markgi999** [comment]
From original email. I bolded the line that needs fixing.

@Linda Lu Cannon<mailto:notifications@github.com>


We got OCV feedback below that seems to indicate a bug in a code sample; the set statement transposes the ‘f’ and ‘d’ in qdf.  Could you look at updating the article?  Thanks!



Help - Database.OpenRecordset method (DAO)
Dim dbs As DAO.Database
Dim qdf As DAO.QueryDef
Dim rst As DAO.Recordset

Set dbs = CurrentDb

'Get the parameter query
Set qfd = dbs.QueryDefs("qryMyParameterQuery")

'Supply the parameter value
qdf.Parameters("EnterStartDate") = Date
qdf.Parameters("EnterEndDate") = Date + 7

'Open a Recordset based on the parameter query
Set rst = qdf.OpenRecordset()


________________________________

**Comment by lindalu-MSFT** [comment]
@Markgi999 I fixed the typo and merged the [change](https://review.docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/database-openrecordset-method-dao?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev11.query%3FappId%3DDev11IDEF1%26l%3Den-US%26k%3Dk(dao360.chm1052939)%3Bk(TargetFrameworkMoniker-Office.Version%3Dv16)%26rd%3Dtrue%3Chttps://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Foffice%2Fclient-developer%2Faccess%2Fdesktop-database-reference%2Fdatabase-openrecordset-method-dao%3Ff1url%3Dhttps%253A%252F%252Fmsdn.microsoft.com%252Fquery%252Fdev11.query%253FappId%253DDev11IDEF1%2526l%253Den-US%2526k%253Dk(dao360.chm1052939)%253Bk(TargetFrameworkMoniker-Office.Version%253Dv16)%2526rd%253Dtrue&data=04%7C01%7Cmarkgi%40microsoft.com%7C7902dc7093e7409a6d7308d6fa69c9bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636971729591074162%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=axySCgCP%2FsuEEKPx7epwCpzeQVPF2TugH2pomTXzb1g%3D&reserved=0) to the live site.
