### ISSUE TITLE
word file dont save in defult path

### ISSUE THREAD

**Issue by e-khani** [MicrosoftDocs/office-developer-client-docs#195]
hi,
I write this code in asp.net c#. it opens word file but don't save it in define path.
<a href="ms-word:nft|u|http://localhost:50921/templates/template.docx|s|http://localhost:50921/presentations">Open in Word</a>

I cant find any answer for why it doesnot work?
please help me asap.
thanks

**Comment by lindalu-MSFT** [comment]
@e-khani Hi, thanks for your question and we're sorry it's taken so long to get back to you! This is a great question to ask the developer community on [StackOverflow](https://stackoverflow.com/). You can tag this word-addin or office-addin or whatever is most appropriate. You might even find the question is answered already. This forum is for reporting actual bugs in the documentation or product, not for how-to questions. thanks!
