### ISSUE TITLE
Is it possible to create a per-monitor DPI aware custom task pane?

### ISSUE THREAD

**Issue by jamesh1971** [MicrosoftDocs/office-developer-client-docs#196]
I want to create a custom task pane that is DPI aware. The problem is I call ICTPFactory.CreateCTP with the ActiveX ProgId, and that creates my task pane content but even though I set the thread to DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE the task pane content window is created as DPI_AWARENESS_CONTEXT_SYSTEM_AWARE (GetWindowDpiAwarenessContext returns SYSTEM_AWARE for the window handle returned by CreateWindowEx). Why would this happen? I can see the window tree using WinSpy++ that CMMOcxHost is SystemAware, and it's parent CMMOcxHostChildWindowMixedMode is per monitor aware. But my control seems to be been forced to be created as only system aware. How is that? Is Excel intercepting CreateWindowEx and forcing the context back to just system aware?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9affc05-6b09-c92b-da08-67758bcb1e87
* Version Independent ID: b1156e9c-3c65-d516-3647-14f5244e2bb4
* Content: [Handle high DPI and DPI scaling in your Office solution](https://docs.microsoft.com/en-us/office/client-developer/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution#feedback)
* Content Source: [docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/ddpi/handle-high-dpi-and-dpi-scaling-in-your-office-solution.md)
* Product: **office365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by jamesh1971** [comment]
Will this be a possible in a future release? Isn't Obviously just a simple registry setting in the COM registration with the Office app, to indicate the add-in is high-DPI aware? Obviously Excel's built-in task-panes are already hosted in DPI aware task panes so the functionality for hosting such task panes is already there? We would really appreciate been able to offer this to our 50,000+ users of Analyse-it.

**Comment by davidchesnut** [comment]
Hi @jamesh1971,

Sorry to hear this is impacting so many of your customers. We of course prefer this was not the case, but for now all we can recommend is the workaround by optimizing Office for compatibility. You have a great request along with thoughts of how to implement it, and we can definitely look into this down the road. We track feature requests on our [UserVoice site](https://officespdev.uservoice.com/). If you can create this as a suggested request in the [Add-in: General category](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=169836) this will keep it on our radar for future backlog planning. Also other developers can review and potentially comment or upvote on it.

Thanks,
Office Extensibility Team

**Comment by jamesh1971** [comment]
I've posted the suggestion at https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/38632276-support-for-high-dpi-taskpanes, if anyone else wants to vote for it.

**Comment by DenisMtfl** [comment]
Why is it closed?

**Comment by jamesh1971** [comment]
Denis, I we created a request for this feature on User Voice, so I closed this issue here. We just need people to vote for it so Microsoft see it's important and implement it. No news yet on if, or when, they will. See and vote it up at https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/38632276-support-for-high-dpi-taskpanes

**Comment by davidchesnut** [comment]
BTW: We also published some samples based on the dynamic DPI article [here](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/dynamic-dpi). While it doesn't address this issue or the UserVoice request, hopefully it is helpful for some of the other scenarios.

**Comment by lindalu-MSFT** [comment]
Hi @jamesh1971! We did close down (well, WE didn't, Microsoft did) and sadly we no longer have your request. But we do have brand now forum for Microsoft 365 developer suggestions! We'd love it if you'd open a request there, too. Please go to [https://aka.ms/m365dev-suggestions](https://aka.ms/m365dev-suggestions) and choose **New idea**. Thanks again, linda
