### ISSUE TITLE
Project sample not found in "Developing a Project Online application using the client-side object model"

### ISSUE THREAD

**Issue by brunoslam** [MicrosoftDocs/office-developer-client-docs#199]
Removed project from github in  "office-developer-client-docs/docs/project/developing-a-project-online-application-using-the-client-side-object-model.md"

[https://docs.microsoft.com/en-us/office/client-developer/project/developing-a-project-online-application-using-the-client-side-object-model#develop-the-application 
](https://docs.microsoft.com/en-us/office/client-developer/project/developing-a-project-online-application-using-the-client-side-object-model#develop-the-application 
)

**Comment by lindalu-MSFT** [comment]
@brunoslam Thanks for finding this. I updated the document and added a link to the resource gallery where you can find more CSOM samples.
