### ISSUE TITLE
irrelevant link from Skype for business

### ISSUE THREAD

**Issue by Brutus11111** [MicrosoftDocs/office-developer-client-docs#229]
Within Skype for business, at the bottom click call forwarding. Select simultaneously ring, select new number. At the popup window, select "get examples". It will open this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88d1d56-b2a7-0e79-74d6-60f84591c103
* Version Independent ID: a02dcc8f-46eb-8f94-a781-a70d1a6b6c82
* Content: [Office client development](https://docs.microsoft.com/en-us/office/client-developer/office-client-development?redirectedfrom=MSDN#feedback)
* Content Source: [docs/office-client-development.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/office-client-development.md)
* Product: **office365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@Brutus11111 Is this a bug in the Skype product or in the actual documentation in this repo?

**Comment by lindalu-MSFT** [comment]
Please use the send a smile or get help links from the product to report product bugs. This repo is for doc issues.
