### ISSUE TITLE
This documentation is incorrect

### ISSUE THREAD

**Issue by carlmarn** [MicrosoftDocs/office-developer-client-docs#310]
I recently opened a support ticket, Case #:25734777, about this problem.
I previously have been using the Office URI scheme, to create a document from a document template, and the newly created document would be saved to a specific location.
The URI scheme that I used was:
ms-word:nft|u|[link-to-document-template]|s|[link-to-a-location-to-save-the-new-file]
The template and the save location are both in SharePoint online.
The result: Word creates a new document based on the template. SharePoint tries to read the SharePoint properties but seems to fail as no fields gets shown in the pane. When I save the document it proposes me to save the document to my OneDrive rather than the location that I specified in the URI.

Please fix this so that it starts working again and before that update the instructions on this page (https://docs.microsoft.com/en-us/office/client-developer/office-uri-schemes) with the above mentioned limitations.

**Comment by lindalu-MSFT** [comment]
Feel free to update the docs and open a PR. You can @lindalu-msft to the PR and I'll review.
