### ISSUE TITLE
Need to update topic which still says preview (https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/excel/configure-udfs-in-excel-online-in-office-online-server-preview.md)

### ISSUE THREAD

**Issue by keyur32** [MicrosoftDocs/office-developer-client-docs#60]
Office Online Server shipped in 2016. We need to verify this topic is valid. If so, need to remove preview from it.

https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/excel/configure-udfs-in-excel-online-in-office-online-server-preview.md

**Comment by keyur32** [comment]
Need to evaluate location in the TOC as well

**Comment by Linda-Editor** [comment]
@keyur32 Hi Keyur, I removed instances of "preview" from this doc, except for the URL. If you think it needs to be moved in the TOC, please let me know where and I'll take care of it. Thanks.
