### ISSUE TITLE
Folder names get changed when origin folder name contains special character like / , % etc

### ISSUE THREAD

**Issue by sarfaraz78615** [MicrosoftDocs/office-developer-client-docs#82]
Folder names get changed when origin folder name contains special character like / , % etc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30b11a7b-b090-5e67-43ee-0b6527810687
* Version Independent ID: 91f2e4ca-7942-eb6c-34d3-2b91b105a248
* Content: [Get a folder based on its folder path](https://docs.microsoft.com/en-us/office/client-developer/outlook/pia/how-to-get-a-folder-based-on-its-folder-path#feedback)
* Content Source: [docs/outlook/pia/how-to-get-a-folder-based-on-its-folder-path.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/outlook/pia/how-to-get-a-folder-based-on-its-folder-path.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Hi @sarfaraz78615 Sorry for the late reply. This repro isn't monitored regularly. I need a little more clarification about this issue. Are you saying that this is a bug or simply something that needs to be documented? Can you please provide me with a few steps to repro this so I can actually see the issue? Also, point out the part of the article that it pertains to. I'll do my best the help resolve this issue.

**Comment by sarfaraz78615** [comment]
Suppose in outlook...folder name is "Sarfaraz%Inbox" or "Sarfaraz/Inbox"

When progrmattically tried to pull the list of all the folders i received different folder names like "Sarfaraz Inbox".

Due to which i cannot use that name to take any action through programming
