### ISSUE TITLE
Office 2016?

### ISSUE THREAD

**Issue by Bartolomeus-649** [MicrosoftDocs/office-developer-client-docs#83]
Where is the latest version of this documentation, one that applies to Office 2016. Or should I still use the Office 2013 SDK with Office 2016??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7d57f58-5d61-4c79-671d-00b0b2300e03
* Version Independent ID: 7561a3ca-75da-c07a-aeb9-ce67114388ab
* Content: [Welcome to the Excel Software Development Kit](https://docs.microsoft.com/en-us/office/client-developer/excel/welcome-to-the-excel-software-development-kit#feedback)
* Content Source: [docs/excel/welcome-to-the-excel-software-development-kit.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/excel/welcome-to-the-excel-software-development-kit.md)
* Product: **excel**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Hi @Bartolomeus-649 The latest Excel developer documentation can be found here: [https://developer.microsoft.com/en-us/excel/docs](https://developer.microsoft.com/en-us/excel/docs). There's also a lot of new info on the new Add-ins (office-js) model here: [https://developer.microsoft.com/en-us/excel](https://developer.microsoft.com/en-us/excel).

**Comment by Bartolomeus-649** [comment]
@lindalu-MSFT At the link you provided there seem to be only stuff about HTML and JavaScript, not at all what I was asking about now, was it?

Where is the real documentation for real, proper addons, extensions and invulnerability with Excel? Those you code in C/C++/C# and which produce a dll...where you have much more access and possibilities than what you get with this new ridicules Javascript based nonsense?

As you can see in my initial post I was referring to the Office/Excel SDK , but since[ the page I linked to in my initial post](https://docs.microsoft.com/en-us/office/client-developer/excel/welcome-to-the-excel-software-development-kit#feedback) only talked about the SDK for Office 2013, and even Office 2010! I asked where to find the SDK for modern versions of Office.

So, again, where is the latest version of [this documentation](https://docs.microsoft.com/en-us/office/client-developer/excel/welcome-to-the-excel-software-development-kit#feedback), one that applies to Office 2016/2019/Office365. **Or should I still use the Office 2013 SDK with Office 2016/2019/Office365**?

**Comment by lindalu-MSFT** [comment]
@Bartolomeus-649 For information about COM or VSTO add-ins, see the [Office 2013 client development](https://docs.microsoft.com/en-us/office/client-developer/office-client-development) documentation. That's the lastest, and you can find it on the [download center](https://www.microsoft.com/en-us/download/details.aspx?id=35567) if you're interested. If you're using VBA, there are updates in the [Office 2016 VBA Reference](https://docs.microsoft.com/en-us/office/vba/api/overview/library-reference/reference-object-library-reference-for-office).

**Comment by Bartolomeus-649** [comment]
@lindalu-MSFT  
So there's no supported solution to use this on Windows 10?

From: https://www.microsoft.com/en-us/download/details.aspx?id=35567
> Supported Operating System
> Windows 7, Windows 8, Windows Server 2003 R2 x64 editions, Windows Server 2008, Windows Server 2008 R2
> This download works with the following applications:
> Microsoft Visual Studio 2005
> -OR-
> Microsoft Visual Studio 2008 for 64-bit XLLs
> Microsoft Excel 2013

Also, is Visual Studio 2008 still supported? And if so, where can I get it?

In the documentation page for the SDKfrom 2014, it say it is only applies to Excel 2013 and Office 2013.
https://docs.microsoft.com/en-us/office/client-developer/excel/welcome-to-the-excel-software-development-kit#feedback
Should we ignore ignore the "Applies to" section in the official Microsoft documentation?
![image](https://user-images.githubusercontent.com/7513795/65168037-018a8f80-da44-11e9-8807-73f8b08b7805.png)
