### ISSUE TITLE
Closing and set to nothing?

### ISSUE THREAD

**Issue by A9G-Data-Droid** [MicrosoftDocs/office-developer-client-docs#84]
I keep seeing this anti-pattern everywhere. One camp sets all objects to nothing religiously. The other camp states that the garbage collector should do this for you. When I see code examples from Microsoft that set objects to nothing right before "End Sub" it makes me question the garbage collector. Is it needed? Is it cargo cult ceremony? Microsoft, we turn to you for answers. Don't lead us astray to worship on the alter of false code correctness.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20cac725-5547-8fb5-1827-64e69fc90ff5
* Version Independent ID: 52846aa1-a496-110c-dd06-a79ff5a90127
* Content: [Recordset.Seek method (DAO)](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/recordset-seek-method-dao#feedback)
* Content Source: [docs/access/desktop-database-reference/recordset-seek-method-dao.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/access/desktop-database-reference/recordset-seek-method-dao.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@A9G-Data-Droid LOL, I see your point. Are you asking us to update the code samples? I assume you're talking about this:

`        Set rst = Nothing
        Set tdf = Nothing
        Set dbs = Nothing` 

We are no longer updating this doc set regularly. You might try asking this on [StackOverflow](https://stackoverflow.com/questions/tagged/access-vba) and see if any developers respond.
