### ISSUE TITLE
Sykpe for Business help ?

### ISSUE THREAD

**Issue by lbloor** [MicrosoftDocs/office-developer-client-docs#85]
This was the destination page for skype for business help, there is nothing relating to skype here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88d1d56-b2a7-0e79-74d6-60f84591c103
* Version Independent ID: a02dcc8f-46eb-8f94-a781-a70d1a6b6c82
* Content: [Office client development](https://docs.microsoft.com/en-us/office/client-developer/office-client-development#feedback)
* Content Source: [docs/office-client-development.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/office-client-development.md)
* Product: **office365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ddillaby** [comment]
I had the same result from Skype for Business Help. Not extremely useful.

**Comment by lindalu-MSFT** [comment]
@lbloor @ddillaby Hey, so sorry for the late response to your question. I'm not sure why the docs team isn't monitoring this repo, and will do my best to find out who we assign issues to. Meanwhile, the [landing page for Skype for Business is here](https://docs.microsoft.com/en-us/skype-sdk/) and the [developer portal is here](https://developer.microsoft.com/en-us/skype). Another great resource is StackOverflow, where you can ask questions to the [Skype developer community](https://stackoverflow.com/questions/tagged/skype-for-business). THANKS for pointing this out! Closing this issue, but feel free to ping me or reopen if you feel the issue still exists.
