### ISSUE TITLE
Skype: skype meetings add-in doesnt work!

### ISSUE THREAD

**Issue by marcellen** [MicrosoftDocs/office-developer-client-docs#87]
Could someone help me? Thank you 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f08461d0-b032-5f34-56a3-7ab8f9aa343e
* Version Independent ID: 6d34dd86-9673-82b9-643d-5328275c4e55
* Content: [Outlook](https://docs.microsoft.com/en-us/office/client-developer/outlook/outlook-home#feedback)
* Content Source: [docs/outlook/outlook-home.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/outlook/outlook-home.md)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@marcellen Please provide information on what the issue is, and steps to reproduce. If you still need assistance, that is. This repro isn't being monitored, but I'll try to direct you to the right person if you provide the repro steps and the errors that you encounter.
