### ISSUE TITLE
Integrating additional cloud storage services

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftDocs/office-developer-client-docs#97]
Provide documentation for integrating 3rd party cloud storage services into MS Office applications' Save As dialogs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88d1d56-b2a7-0e79-74d6-60f84591c103
* Version Independent ID: a02dcc8f-46eb-8f94-a781-a70d1a6b6c82
* Content: [Office client development](https://docs.microsoft.com/en-us/office/client-developer/office-client-development#feedback)
* Content Source: [docs/office-client-development.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/office-client-development.md)
* Product: **office365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@Reezaali Reeza, do you know of any Office add-in documentation that discusses 3rd party cloud storage integration?

**Comment by Reezaali** [comment]
@jozefizso    You can integrate 3rd party services using the Office (Web) add-ins model. Have you considered using that model?

**Comment by lindalu-MSFT** [comment]
FYI here's the[ Office Add-ins platform overview](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins) documentation.
