### ISSUE TITLE
Call AddNew again functions as calling Update

### ISSUE THREAD

**Issue by Janmanden** [MicrosoftDocs/office-developer-client-docs#98]
"If you issue an AddNew and then perform any operation that moves to another record, but without using Update, your changes are lost without warning."

Not quite. If you move to another record by calling AddNew it works just like using Update. In other words, you don't need to use Update at all as long as you call AddNew. Even work on an existing record can be "Updated" with the oddity of an AddNew command, but doing that means that you can't keep working on the same record of course. 

rstTmp.AddNew
...
rstTmp.AddNew
...
rstTmp.Update/AddNew
(End)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec0046e-f656-0baf-5290-2a2d4a400ae8
* Version Independent ID: 708665e8-2845-6b33-27d2-0d629ea67d4f
* Content: [Recordset.AddNew method (DAO)](https://docs.microsoft.com/en-us/office/client-developer/access/desktop-database-reference/recordset-addnew-method-dao#feedback)
* Content Source: [docs/access/desktop-database-reference/recordset-addnew-method-dao.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/access/desktop-database-reference/recordset-addnew-method-dao.md)
* Product: **access**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Hi @Janmanden If you have a suggestion to improve the documentation, please open a PR and I'll review. We don't have resources to update this docset and appreciate your help. Thanks!
