### ISSUE TITLE
Content Controls in a Table

### ISSUE THREAD

**Issue by spiritsip** [MicrosoftDocs/office-developer-client-docs#99]
How do you make the name of an xml-bound content control wrap when you add it inside a table? Just adding a plain-text control makes it so that the column won't get narrower than the name of the content control. With regular text, you would just add a hyphen, but that would break an xml-bound content control I think.

Example use case: I might want to show a quantity value in a table that will only be 2 characters or less (e.g. values 1 - 99), but because the field is called "quantity" I can't make the column narrower than to accommodate all 8 characters in the word quantity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6382eab7-9d88-50e1-36a4-22879a243d3c
* Version Independent ID: 04ba092a-87c8-5369-4373-6c81a8fc5de7
* Content: [Content controls in Word](https://docs.microsoft.com/en-us/office/client-developer/word/content-controls-in-word)
* Content Source: [docs/word/content-controls-in-word.md](https://github.com/MicrosoftDocs/office-developer-client-docs/blob/master/docs/word/content-controls-in-word.md)
* Product: **word**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
@spiritsip Hi, thanks for your question. We're no longer regularly updating this content so we don't have anyone regularly monitoring this repo. This is a good question for StackOverflow. Have you tried asking the developer community there questions about your Word or Office code? You'll likely get a quick response if you ask there! Try going to SO andusing the [openxml](https://stackoverflow.com/questions/tagged/openxml) tag or one of the Office developer tags.
